CREATE TABLE CAR_INFO (
    MODEL_NUM INT AUTO_INCREMENT PRIMARY KEY,
    MODEL_NAME VARCHAR(100) NOT NULL,
    PRICE INT DEFAULT,
    BRAND VARCHAR(50) NOT NULL
);

CREATE TABLE COLOR_INFO (
    COLOR VARCHAR(50) PRIMARY KEY
);

CREATE TABLE SALES_INFO (
    SALE_NUM INT AUTO_INCREMENT PRIMARY KEY,
    BUYER_NAME VARCHAR(50) NOT NULL,
    BUYER_TEL VARCHAR(20) NOT NULL,
    COLOR VARCHAR(50) NOT NULL,
    MODEL_NUM INT NOT NULL,
    SALES_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MODEL_NUM) REFERENCES CAR_INFO(MODEL_NUM)
    FOREIGN KEY COLOR REFERENCES COLOR_INFO(COLOR)
);
CREATE TABLE CARS_CATE (
	CATE_NUM INT PRIMARY KEY AUTO_INCREMENT,
	CATE_NAME VARCHAR(50) NOT NULL
)

SELECT *
FROM SALES_INFO;
SELECT * 
FROM CAR_INFO;

SELECT SALES_NUM
,	BUYER_NAME
,	BUYER_TEL
,	SALES_DATE
,	COLOR
,	C.MODEL_NAME
,	C.PRICE
FROM sales_info S INNER JOIN car_info C
ON S.MODEL_NUM = C.MODEL_NUM
ORDER BY SALES_DATE DESC
