-- CAR_INFO 생성쿼리
 
CREATE TABLE CAR_INFO (
    MODEL_NUM INT  PRIMARY KEY AUTO_INCREMENT,
    MODEL_NAME VARCHAR(100) NOT NULL,
    PRICE INT DEFAULT 0,
    BRAND VARCHAR(50) NOT NULL
);

-- COLOR_INFO 생성쿼리 및 데이터 삽입
CREATE TABLE COLOR_INFO (
    COLOR VARCHAR(50) PRIMARY KEY
);
INSERT INTO COLOR_INFO (COLOR) VALUES ('레드');
INSERT INTO COLOR_INFO (COLOR) VALUES ('실버');
INSERT INTO COLOR_INFO (COLOR) VALUES ('블랙');
INSERT INTO COLOR_INFO (COLOR) VALUES ('화이트');
INSERT INTO COLOR_INFO (COLOR) VALUES ('그레이');

-- SALES_INFO 생성쿼리
CREATE TABLE SALES_INFO (
    SALES_NUM INT AUTO_INCREMENT PRIMARY KEY,
    BUYER_NAME VARCHAR(50) NOT NULL,
    BUYER_TEL VARCHAR(20) NOT NULL,
    COLOR VARCHAR(50) NOT NULL,
    MODEL_NUM INT NOT NULL,
    SALES_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MODEL_NUM) REFERENCES CAR_INFO(MODEL_NUM),
    FOREIGN KEY (COLOR) REFERENCES COLOR_INFO(COLOR)
);

-- CARS_CATE 생성쿼리 및 데이터삽입
CREATE TABLE CARS_CATE (
	CATE_NUM INT PRIMARY KEY AUTO_INCREMENT,
	CATE_NAME VARCHAR(50) NOT NULL
);
INSERT INTO CARS_CATE (CATE_NAME) VALUES ('현대');
INSERT INTO CARS_CATE (CATE_NAME) VALUES ('기아');
INSERT INTO CARS_CATE (CATE_NAME) VALUES ('제네시스');

DROP TABLE CAR_INFO;
-- 조회
SELECT *
FROM SALES_INFO;
SELECT * 
FROM CAR_INFO;
SELECT *
FROM CARS_CATE;


FROM 
